@startuml
!include .\\.\Models\Alquiler.puml
!include .\\.\Models\ApplicationUser.puml
!include .\\.\Models\ClaseDeportiva.puml
!include .\\.\Models\ClaseInscrita.puml
!include .\\.\Models\Competicion.puml
!include .\\.\Models\CompeticionInscrita.puml
!include .\\.\Models\Inscripcion.puml
!include .\\.\Models\Material.puml
!include .\\.\Models\MaterialAlquilado.puml
!include .\\.\Models\MetodoPago.puml
!include .\\.\Models\Pista.puml
!include .\\.\Models\PistaReservada.puml
!include .\\.\Models\Reserva.puml
!include .\\.\Models\TipoDeporte.puml
!include .\\.\Models\TipoMaterial.puml
@enduml
