@startuml
!include .\\.\Models\ApplicationUser.puml
!include .\\.\Models\Competicion.puml
!include .\\.\Models\InscripcionCompeticion.puml
!include .\\.\Models\Material.puml
!include .\\.\Models\MetodoPago.puml
!include .\\.\Models\Pista.puml
@enduml
