@startuml
class Alquiler {
    + IdAlquiler : int <<get>> <<set>>
    + NombreUsuario : string <<get>> <<set>>
    + ApellidosUsuario : string <<get>> <<set>>
    + DNI : string <<get>> <<set>>
    + NumeroTelefono : string <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
}
class "IList`1"<T> {
}
Alquiler --> "FechaAlquiler" DateTime
Alquiler --> "MetodoPago" MetodoPago
Alquiler o-> "MaterialesAlquilados<MaterialAlquilado>" "IList`1"
@enduml
