@startuml
class Competicion {
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Plazas : int <<get>> <<set>>
    + Lugar : string <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + TipoDeporteId : int <<get>> <<set>>
}
class "IList`1"<T> {
}
Competicion --> "Fecha" DateTime
Competicion o-> "TipoDeporte" TipoDeporte
Competicion o-> "CompeticionesInscritas<CompeticionInscrita>" "IList`1"
@enduml
