@startuml
class Material {
    + IdMaterial : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + Cantidad : int <<get>> <<set>>
    + TipoMaterialId : int <<get>> <<set>>
    + TipoDeporteId : int <<get>> <<set>>
}
Material o-> "TipoMaterial" TipoMaterial
Material o-> "TipoDeporte" TipoDeporte
@enduml
