@startuml
class Material {
    + IdMaterial : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + Cantidad : int <<get>> <<set>>
    + TipoMaterialId : int <<get>> <<set>>
    + TipoDeporteId : int <<get>> <<set>>
}
class "IList`1"<T> {
}
Material o-> "TipoMaterial" TipoMaterial
Material o-> "TipoDeporte" TipoDeporte
Material o-> "MaterialesAlquilados<MaterialAlquilado>" "IList`1"
@enduml
