@startuml
class TipoDeporte {
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Descripcion : string? <<get>> <<set>>
}
class "IList`1"<T> {
}
TipoDeporte o-> "Competiciones<Competicion>" "IList`1"
TipoDeporte o-> "Materiales<Material>" "IList`1"
@enduml
